AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  app1:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template_app1.yml
  app2:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template_app2.yml
