AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: test

Resources:
  ApiGatewayApi1:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Name: api1

  app1:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template_app1.yml

  app2:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template_app2.yml
      Parameters:
        Stage: !Ref Stage
        BucketTest: !Ref S3Bucket

  api1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: api1
      CodeUri: handlers/api1
      Handler: api1
      Runtime: go1.x
      Events:
        HttpGet:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi1
            Path: '/v1/test1'
            Method: Get

  S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aws-sam-nested-application-test-bucket-0-001
