AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev
  BucketTest:
    Type: String

Globals:
  Function:
    Runtime: go1.x
    Timeout: 900
    Environment:
      Variables:
        STAGE: !Ref Stage

Resources:
  App2Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app2
      CodeUri: handlers/app2
      Handler: app2

  S3Bucket2001:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aws-sam-nested-application-test-bucket-2-001
