AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  App1Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app1
      CodeUri: handlers/app1
      Handler: app1
      Runtime: go1.x
